### ISSUE TITLE
HttpClient cannot be resolved to a type.

### ISSUE THREAD

**Issue by ItsAndrewDev** [RaphiMC/MinecraftAuth#33]
MinecraftAuth Versions tested: 4.0.2 + Latest (gradlew build)
Java version: 8, 11
![image](https://github.com/user-attachments/assets/b18a6a38-7a45-490f-82ab-46c4e8ba8054)

**Comment by RaphiMC** [comment]
What happens if you run `gradlew build`? Does that work?

**Comment by ItsAndrewDev** [comment]
Yes, ``gradlew build`` produces no errors.
![image](https://github.com/user-attachments/assets/b4e3bc88-3af5-44ae-a946-02ff647c8591)

**Comment by ItsAndrewDev** [comment]
Tried again after running ``gradlew``
![image](https://github.com/user-attachments/assets/99f5aa46-22d6-42ec-866d-4df40f9c00df)

**Comment by RaphiMC** [comment]
Not exactly what I meant. I thought your project uses gradle. Anyway, what buildsystem is your project using and how are you including MinecraftAuth?

**Comment by ItsAndrewDev** [comment]
I'm using Eclipse IDE, imported the gradlew built MinecraftAuth jar into the Build path.
![image](https://github.com/user-attachments/assets/46f4a10e-06a2-4c03-9ef1-e9f063a58b9b)

**Comment by RaphiMC** [comment]
You should consider using a proper build system like maven or gradle which would automatically download dependencies. If you don't want that you have to download the jars of the dependencies of MinecraftAuth yourself from maven central (Download the jar of everything listed under Compile Dependencies: https://mvnrepository.com/artifact/net.raphimc/MinecraftAuth/4.0.2)

**Comment by ItsAndrewDev** [comment]
Oh yes I forgot about the dependencies. Thanks!
